# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='model',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\x12\x05model\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x06\n\x10HeartbeatMessage\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12\x19\n\x11\x41MResourceLimitMB\x18\x02 \x01(\x05\x12\x1d\n\x15\x41MResourceLimitVCores\x18\x03 \x01(\x05\x12\x18\n\x10UsedAMResourceMB\x18\x04 \x01(\x05\x12\x1c\n\x14UsedAMResourceVCores\x18\x05 \x01(\x05\x12\x15\n\rAppsSubmitted\x18\x06 \x01(\x05\x12\x13\n\x0b\x41ppsRunning\x18\x07 \x01(\x05\x12\x13\n\x0b\x41ppsPending\x18\x08 \x01(\x05\x12\x15\n\rAppsCompleted\x18\t \x01(\x05\x12\x12\n\nAppsKilled\x18\n \x01(\x05\x12\x12\n\nAppsFailed\x18\x0b \x01(\x05\x12$\n\x1c\x41ggregateContainersPreempted\x18\x0c \x01(\x05\x12\x1a\n\x12\x41\x63tiveApplications\x18\r \x01(\x05\x12\x35\n-AppAttemptFirstContainerAllocationDelayNumOps\x18\x0e \x01(\x05\x12\x36\n.AppAttemptFirstContainerAllocationDelayAvgTime\x18\x0f \x01(\x02\x12\x13\n\x0b\x41llocatedMB\x18\x10 \x01(\x05\x12\x17\n\x0f\x41llocatedVCores\x18\x11 \x01(\x05\x12\x1b\n\x13\x41llocatedContainers\x18\x12 \x01(\x05\x12$\n\x1c\x41ggregateContainersAllocated\x18\x13 \x01(\x05\x12#\n\x1b\x41ggregateContainersReleased\x18\x14 \x01(\x05\x12\x13\n\x0b\x41vailableMB\x18\x15 \x01(\x05\x12\x17\n\x0f\x41vailableVCores\x18\x16 \x01(\x05\x12\x11\n\tPendingMB\x18\x17 \x01(\x05\x12\x15\n\rPendingVCores\x18\x18 \x01(\x05\x12\x19\n\x11PendingContainers\x18\x19 \x01(\x05\x12-\n\tTimestamp\x18\x1a \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rNumberOfNodes\x18\x1b \x01(\x05\x12\x0c\n\x04\x43ost\x18\x1c \x01(\x02\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_HEARTBEATMESSAGE = _descriptor.Descriptor(
  name='HeartbeatMessage',
  full_name='model.HeartbeatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_name', full_name='model.HeartbeatMessage.cluster_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AMResourceLimitMB', full_name='model.HeartbeatMessage.AMResourceLimitMB', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AMResourceLimitVCores', full_name='model.HeartbeatMessage.AMResourceLimitVCores', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UsedAMResourceMB', full_name='model.HeartbeatMessage.UsedAMResourceMB', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UsedAMResourceVCores', full_name='model.HeartbeatMessage.UsedAMResourceVCores', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AppsSubmitted', full_name='model.HeartbeatMessage.AppsSubmitted', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AppsRunning', full_name='model.HeartbeatMessage.AppsRunning', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AppsPending', full_name='model.HeartbeatMessage.AppsPending', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AppsCompleted', full_name='model.HeartbeatMessage.AppsCompleted', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AppsKilled', full_name='model.HeartbeatMessage.AppsKilled', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AppsFailed', full_name='model.HeartbeatMessage.AppsFailed', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AggregateContainersPreempted', full_name='model.HeartbeatMessage.AggregateContainersPreempted', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ActiveApplications', full_name='model.HeartbeatMessage.ActiveApplications', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AppAttemptFirstContainerAllocationDelayNumOps', full_name='model.HeartbeatMessage.AppAttemptFirstContainerAllocationDelayNumOps', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AppAttemptFirstContainerAllocationDelayAvgTime', full_name='model.HeartbeatMessage.AppAttemptFirstContainerAllocationDelayAvgTime', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AllocatedMB', full_name='model.HeartbeatMessage.AllocatedMB', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AllocatedVCores', full_name='model.HeartbeatMessage.AllocatedVCores', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AllocatedContainers', full_name='model.HeartbeatMessage.AllocatedContainers', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AggregateContainersAllocated', full_name='model.HeartbeatMessage.AggregateContainersAllocated', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AggregateContainersReleased', full_name='model.HeartbeatMessage.AggregateContainersReleased', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AvailableMB', full_name='model.HeartbeatMessage.AvailableMB', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AvailableVCores', full_name='model.HeartbeatMessage.AvailableVCores', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PendingMB', full_name='model.HeartbeatMessage.PendingMB', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PendingVCores', full_name='model.HeartbeatMessage.PendingVCores', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PendingContainers', full_name='model.HeartbeatMessage.PendingContainers', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='model.HeartbeatMessage.Timestamp', index=25,
      number=26, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NumberOfNodes', full_name='model.HeartbeatMessage.NumberOfNodes', index=26,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Cost', full_name='model.HeartbeatMessage.Cost', index=27,
      number=28, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=866,
)

_HEARTBEATMESSAGE.fields_by_name['Timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['HeartbeatMessage'] = _HEARTBEATMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartbeatMessage = _reflection.GeneratedProtocolMessageType('HeartbeatMessage', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:model.HeartbeatMessage)
  ))
_sym_db.RegisterMessage(HeartbeatMessage)


# @@protoc_insertion_point(module_scope)
